version: 2
jobs:
    build:
        docker: # run the steps with Docker 
            - image: circleci/php:7.1-node-browsers # ...with this image as the primary container; this is where all `steps` will run
        working_directory: ~/laravel # directory where steps will run
        steps:
        - checkout
        - run: sudo composer self-update
        - run:
            name: Sudo update
            command: sudo apt-get update && sudo apt-get install -y --no-install-recommends apt-utils
        - run:
            name: Install git ftp
            command: sudo apt-get -qq install git-ftp
        - run:
            name: Push to site
            command: | 
                if [ "$CIRCLE_BRANCH" == "laravel57" ];
                then
                    git config git-ftp.url "ftp://hammernemt.dk/live"
                    git config git-ftp.user "${FTP_USERNAME}"
                    git config git-ftp.password "${FTP_PASSWORD}"
                    git ftp push
                    echo "Pushing to live"
                fi
                if [ "$CIRCLE_BRANCH" == "dev" ];
                then
                    git config git-ftp.url "ftp://hammernemt.dk/dev"
                    git config git-ftp.user "${FTP_USERNAME}"
                    git config git-ftp.password "${FTP_PASSWORD}"
                    git ftp init
                    git ftp push
                    echo "Pushing to dev"
                fi
                echo $CIRCLE_BRANCH
                
        - run: 
            name: DONE!
            command: echo DONE
            
