version: 2
jobs:
    build:
    master_deploy:
        docker: # run the steps with Docker 
            - image: circleci/php:7.1-node-browsers # ...with this image as the primary container; this is where all `steps` will run
        working_directory: ~/laravel # directory where steps will run
        branches:
            only:
                - master
        steps:
        - checkout
        - run: sudo composer self-update
        - run:
            name: Sudo update
            command: sudo apt-get update && sudo apt-get install -y --no-install-recommends apt-utils
        - run:
            name: Install git ftp
            command: sudo apt-get -qq install git-ftp
        - run:
            name: Push to site
            command: git ftp push --user "${FTP_USERNAME}" --passwd "${FTP_PASSWORD}" ftp://hammernemt.dk/live
dev_deploy:
        docker: # run the steps with Docker 
            - image: circleci/php:7.1-node-browsers # ...with this image as the primary container; this is where all `steps` will run
        working_directory: ~/laravel # directory where steps will run
        branches:
            only:
                - dev
        steps:
        - checkout
        - run: sudo composer self-update
        - run:
            name: Sudo update
            command: sudo apt-get update && sudo apt-get install -y --no-install-recommends apt-utils
        - run:
            name: Install git ftp
            command: sudo apt-get -qq install git-ftp
        - run:
            name: Push to site
            command: git ftp push --user "${FTP_USERNAME}" --passwd "${FTP_PASSWORD}" ftp://hammernemt.dk/dev
   