version: 2
jobs:
    build:
        docker: # run the steps with Docker 
            - image: circleci/php:7.1-node-browsers # ...with this image as the primary container; this is where all `steps` will run
        working_directory: ~/laravel # directory where steps will run
        steps:
        - checkout
        - run: sudo composer self-update
    deploy:
        machine:
            enabled: true
        working_directory: ~/laravel # directory where steps will run
        steps:
        - run:
            name: Sudo update
            command: sudo apt-get update && sudo apt-get install -y --no-install-recommends apt-utils
        - run:
            name: Install git ftp
            command: sudo apt-get -qq install git-ftp
        -run :
            name: Push to site
            command: git ftp push --user "${FTP_USERNAME}" --passwd "${FTP_PASSWORD}" ftp://hammernemt.dk/live
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy